### ISSUE TITLE
issue: 2

### ISSUE THREAD

**Issue by MacGyverPY** [Wayzware/MagicalHearse#4]
So the issue, 

this mod removes the need for hearses, thought it would remove the Homeless People too...
it doesnt.. maybe i mis-read that.. but that should be the next mod... just remove Homeless ppl, either by locking them up or aliens come and grab them

**Comment by Wayzware** [comment]
Well, homeless people are still alive, so they would not be picked up by hearses normally.

I will consider making that a separate mod though.
